### PR TITLE
corrected typo in attribute

### PR DESCRIPTION
**Pull request by vladox**
This was triggering an exception when saving a product

### CODE REVIEW

**Comment by ghost** [comment]
It took me a while to find the difference. I even used python to double check it :+1:

**Comment by vladox** [comment]
great thanks for the merge!  I've a whole lot of changes for the encoding problems do you want me to do a pull request for those as well?

**Comment by ghost** [comment]
We have a solution in our branch 9.0, that will be ported to branch 8.0. If you can wait, you can check if it solves your problems :+1:

**Comment by vladox** [comment]
OK I've seen your changes in branch 9.0 I'll test it as soon as you are ready with them

**Comment by ghost** [comment]
#33 tries to solve the unicode error

**Pull request merged**
